const cartas = [
  {
    id: 1,
    name: 'El Loco',
    desc: '',
    img: 'images/cards/card_00.jpg',
  },
  {
    id: 2,
    name: 'El Mago',
    desc: '',
    img: 'images/cards/card_01.jpg',
  },
  {
    id: 3,
    name: 'La Sacerdotisa',
    desc: '',
    img: 'images/cards/card_02.jpg',
  },
  {
    id: 4,
    name: 'La Emperatriz',
    desc: '',
    img: 'images/cards/card_03.jpg',
  },
  {
    id: 5,
    name: 'El Emperador',
    desc: '',
    img: 'images/cards/card_04.jpg',
  },
  {
    id: 6,
    name: 'El Hierofante',
    desc: '',
    img: 'images/cards/card_05.jpg',
  },
  {
    id: 7,
    name: 'Los Amantes',
    desc: '',
    img: 'images/cards/card_06.jpg',
  },
  {
    id: 8,
    name: 'El Carro',
    desc: '',
    img: 'images/cards/card_07.jpg',
  },
  {
    id: 9,
    name: 'Fuerza',
    desc: '',
    img: 'images/cards/card_08.jpg',
  },
  {
    id: 10,
    name: 'El Ermitaño',
    desc: '',
    img: 'images/cards/card_09.jpg',
  },
  {
    id: 11,
    name: 'Rueda de la Fortuna',
    desc: '',
    img: 'images/cards/card_10.jpg',
  },
  {
    id: 12,
    name: 'Justicia',
    desc: '',
    img: 'images/cards/card_11.jpg',
  },
  {
    id: 13,
    name: 'El Colgado',
    desc: '',
    img: 'images/cards/card_12.jpg',
  },
  {
    id: 14,
    name: 'Muerte',
    desc: '',
    img: 'images/cards/card_13.jpg',
  },
  {
    id: 15,
    name: 'Templanza',
    desc: '',
    img: 'images/cards/card_14.jpg',
  },
  {
    id: 16,
    name: 'El Diablo',
    desc: '',
    img: 'images/cards/card_15.jpg',
  },
  {
    id: 17,
    name: 'La Torre',
    desc: '',
    img: 'images/cards/card_16.jpg',
  },
  {
    id: 18,
    name: 'La Estrella',
    desc: '',
    img: 'images/cards/card_17.jpg',
  },
  {
    id: 19,
    name: 'La Luna',
    desc: '',
    img: 'images/cards/card_18.jpg',
  },
  {
    id: 20,
    name: 'El Sol',
    desc: '',
    img: 'images/cards/card_19.jpg',
  },
  {
    id: 21,
    name: 'Juicio',
    desc: '',
    img: 'images/cards/card_20.jpg',
  },
  {
    id: 22,
    name: 'El Mundo',
    desc: '',
    img: 'images/cards/card_21.jpg',
  },
  {
    id: 23,
    name: 'Sota de Bastos',
    desc: '',
    img: 'images/cards/card_22.jpg',
  },
  {
    id: 24,
    name: 'Sota de Copas',
    desc: '',
    img: 'images/cards/card_23.jpg',
  },
  {
    id: 25,
    name: 'Sota de Oros',
    desc: '',
    img: 'images/cards/card_24.jpg',
  },
  {
    id: 26,
    name: 'Sota de Espadas',
    desc: '',
    img: 'images/cards/card_25.jpg',
  },
  {
    id: 27,
    name: 'Caballero de Bastos',
    desc: '',
    img: 'images/cards/card_26.jpg',
  },
  {
    id: 28,
    name: 'Caballero de Copas',
    desc: '',
    img: 'images/cards/card_27.jpg',
  },
  {
    id: 29,
    name: 'Caballero de Oros',
    desc: '',
    img: 'images/cards/card_28.jpg',
  },
  {
    id: 30,
    name: 'Caballero de Espadas',
    desc: '',
    img: 'images/cards/card_29.jpg',
  },
  {
    id: 31,
    name: 'Reina de Bastos',
    desc: '',
    img: 'images/cards/card_30.jpg',
  },
  {
    id: 32,
    name: 'Reina de Copas',
    desc: '',
    img: 'images/cards/card_31.jpg',
  },
  {
    id: 33,
    name: 'Reina de Oros',
    desc: '',
    img: 'images/cards/card_32.jpg',
  },
  {
    id: 34,
    name: 'Reina de Espadas',
    desc: '',
    img: 'images/cards/card_33.jpg',
  },
  {
    id: 35,
    name: 'Rey de Bastos',
    desc: '',
    img: 'images/cards/card_34.jpg',
  },
  {
    id: 36,
    name: 'Rey de Copas',
    desc: '',
    img: 'images/cards/card_35.jpg',
  },
  {
    id: 37,
    name: 'Rey de Oros',
    desc: '',
    img: 'images/cards/card_36.jpg',
  },
  {
    id: 38,
    name: 'Rey de Espadas',
    desc: '',
    img: 'images/cards/card_37.jpg',
  },
  {
    id: 39,
    name: 'Angel del Aire',
    desc: '',
    img: 'images/cards/card_38.jpg',
  },
  {
    id: 40,
    name: 'Angel de la Tierra',
    desc: '',
    img: 'images/cards/card_39.jpg',
  },
  {
    id: 41,
    name: 'Angel de Fuego',
    desc: '',
    img: 'images/cards/card_40.jpg',
  },
  {
    id: 42,
    name: 'Angel del Agua',
    desc: '',
    img: 'images/cards/card_41.jpg',
  },
]
